package com.logiconnect.platform.audit.entity;

/**
 * Standard enterprise audit action types.
 */
public enum AuditAction {
    // Authentication lifecycle
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_CHANGED,
    ACCOUNT_LOCKED,
    TOKEN_REFRESHED,

    // Department lifecycle
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_DEACTIVATED,

    // Team lifecycle
    TEAM_CREATED,
    TEAM_UPDATED,
    TEAM_DEACTIVATED,

    // Employee lifecycle
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_STATUS_CHANGED,
    EMPLOYEE_DEACTIVATED,

    // Messaging lifecycle
    CONVERSATION_CREATED,
    GROUP_MEMBER_ADDED,
    GROUP_MEMBER_REMOVED,
    MESSAGE_EDITED,
    MESSAGE_DELETED,

    // Channel lifecycle & moderation
    CHANNEL_CREATED,
    CHANNEL_UPDATED,
    CHANNEL_ARCHIVED,
    CHANNEL_MEMBER_ADDED,
    CHANNEL_MEMBER_REMOVED,
    CHANNEL_MESSAGE_PINNED,
    CHANNEL_MESSAGE_UNPINNED,

    // Announcement lifecycle
    ANNOUNCEMENT_CREATED,
    ANNOUNCEMENT_UPDATED,
    ANNOUNCEMENT_SCHEDULED,
    ANNOUNCEMENT_PUBLISHED,
    ANNOUNCEMENT_CANCELLED,
    ANNOUNCEMENT_ARCHIVED,
    ANNOUNCEMENT_ACKNOWLEDGED
}
